### ISSUE TITLE
onLayoutChildren() is convoluted

### ISSUE THREAD

**Issue by eazyigz** [antoniolg/RecyclerViewExtensions#14]
Hello,
I appreciate your sample code.  However, the onLayoutChildren() method you made is very convoluted.  It is 226 lines of spaghetti code!  I am wondering if there is any way to simplify this method.  I would be happy to contribute if you give me some guidance here.  Sorry, I am just a beginner with RecyclerViews.

**Comment by antoniolg** [comment]
Sorry, that´s code from Google, the one I could extract from one of layouts in support library. I´m not planning to update this example because it´s based on L preview and things changed a lot so far. 

If you are looking for a real library to help with RecyclerView, take a look at https://github.com/lucasr/twoway-view/ . Don´t know its current status either anyway.

**Comment by antoniolg** [comment]
Of course, but that example doesn´t have anything to do with this. This was an example of how to build a GridViewLayoutManager because the existing one in current support library didn´t existed in L preview. So this was a way to implement it.

**Comment by eazyigz** [comment]
~"but that example doesn´t have anything to do with this"
Sure it does!  There is a Grid Layout Manager in that project.  See these screenshots:
![gridlayoutmanager](https://cloud.githubusercontent.com/assets/201209/5648458/b6b02036-965c-11e4-9cf3-3bef74978815.png)
![recyclerview](https://cloud.githubusercontent.com/assets/201209/5648457/b6ab7360-965c-11e4-877e-0b7b5389beae.png)
